name: Python Test Workflow

on:
  push:
    branches-ignore:
      - 'master'
  workflow_dispatch:
    
jobs:
  Python_Test_Workflow
    runs-on: [ windows-2025 ]
    steps:
    - name: Test Output
      run: |
        dir
        set
      shell: cmd